USE [Gilead_KT]
GO

/****** Object:  View [dbo].[CONVERSION]    Script Date: 2/15/2023 8:01:27 PM ******/
DROP VIEW [dbo].[CONVERSION]
GO

/****** Object:  View [dbo].[CONVERSION]    Script Date: 2/15/2023 8:01:27 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE   VIEW [dbo].[CONVERSION] AS
SELECT E.EMPLOYEE_ID,
CONCAT(E.FIRST_NAME,' ',E.LAST_NAME) AS FULL_NAME,
CONCAT(E.EMAIL,'@deloitte.com') AS EMAIL,
CONCAT('+91',REPLACE(E.PHONE_NUMBER,'.','')) AS PHONE_NUMBER,
FORMAT(E.HIRE_DATE,'dd-MM-yyyy') AS HIRE_DATE,
E.JOB_ID,
E.SALARY,
ISNULL(E.COMMISSION_PCT,0) AS COMMISSION_PCT,
ISNULL(CAST(E.MANAGER_ID AS VARCHAR),' ') AS MANAGER_ID,
ISNULL(CAST(E.DEPARTMENT_ID AS VARCHAR),' ') AS DEPARTMENT_ID,
D.DEPARTMENT_NAME
FROM EMPLOYEES E LEFT JOIN DEPARTMENTS D
ON E.DEPARTMENT_ID=D.DEPARTMENT_ID
GO


