use gilead_KT

------7.2(I)-----

SELECT EMPLOYEE_ID,DEPARTMENT_ID, COUNT (EMPLOYEE_ID)OVER (PARTITION BY DEPARTMENT_ID ORDER BY DEPARTMENT_ID) AS COUNT,LAST_NAME FROM EMPLOYEES

-----7.2(I)--------

------7.2(II)-----
SELECT * FROM(
SELECT DEPARTMENT_ID,SALARY,DENSE_RANK ()OVER (PARTITION BY DEPARTMENT_ID ORDER BY SALARY DESC) AS DENSERANK,LAST_NAME FROM EMPLOYEES
)H WHERE DENSERANK=2

------7.2(II)-----

------7.2(III)-----
SELECT DEPARTMENT_ID,SALARY,RANK ()OVER (PARTITION BY DEPARTMENT_ID ORDER BY SALARY DESC) AS R_ANK,LAST_NAME FROM EMPLOYEES
------7.2(III)-----

------7.2(IV)-----
select * from (
select department_id,salary,rank()over (partition by department_id order by salary ) as position,last_name from EMPLOYEES
)a where position =1

------7.2(IV)-----


SELECT FIRST_NAME,SALARY,DEPARTMENT_ID,ROW_NUMBER()OVER(PARTITION BY DEPARTMENT_ID ORDER BY SALARY asc) AS ROW_NUMBER,
RANK() OVER(PARTITION BY DEPARTMENT_ID ORDER BY SALARY asc)AS R_ANK,DENSE_RANK() OVER(PARTITION BY DEPARTMENT_ID ORDER BY SALARY asc) AS 
DENSERANK FROM EMPLOYEES