use Gilead_KT

select * from employees
select * from JOB_HISTORY
select * from DEPARTMENTS

select last_name,hire_date from employees where
department_id =( select department_id from EMPLOYEES where last_name='Zlotkey') and last_name!='Zlotkey'

SELECT LAST_NAME,EMPLOYEE_ID FROM EMPLOYEES
WHERE SALARY>(SELECT AVG(SALARY) FROM EMPLOYEES)

SELECT LAST_NAME,EMPLOYEE_ID FROM EMPLOYEES
WHERE LAST_NAME LIKE 'U%'

SELECT LAST_NAME,DEPARTMENT_ID,JOB_ID FROM EMPLOYEES
WHERE DEPARTMENT_ID IN(SELECT DEPARTMENT_ID FROM DEPARTMENTS WHERE LOCATION_ID = 1700)

SELECT LAST_NAME,SALARY FROM EMPLOYEES
WHERE MANAGER_ID IN (SELECT EMPLOYEE_ID FROM EMPLOYEES WHERE LAST_NAME='King')

SELECT EMPLOYEE_ID,LAST_NAME,SALARY FROM EMPLOYEES WHERE SALARY >
(SELECT AVG(SALARY) FROM EMPLOYEES WHERE LAST_NAME LIKE '%U%')

SELECT LAST_NAME,DEPARTMENT_ID,SALARY FROM EMPLOYEES WHERE
SALARY IN(SELECT SALARY FROM EMPLOYEES) AND DEPARTMENT_ID IN (SELECT DEPARTMENT_ID FROM EMPLOYEES
WHERE COMMISSION_PCT IS NOT NULL)

SELECT LAST_NAME,DEPARTMENT_NAME,SALARY FROM EMPLOYEES E,DEPARTMENTS D
WHERE SALARY IN(SELECT SALARY FROM EMPLOYEES) AND COMMISSION_PCT IN (SELECT COMMISSION_PCT FROM EMPLOYEES
WHERE E.DEPARTMENT_ID=D.DEPARTMENT_ID AND LOCATION_ID='1700')

SELECT LAST_NAME,HIRE_DATE,CAST(SALARY AS INT) FROM EMPLOYEES
WHERE SALARY IN(SELECT SALARY FROM EMPLOYEES) AND (LAST_NAME='KOCHHAR')

SELECT LAST_NAME,JOB_ID,SALARY FROM EMPLOYEES WHERE SALARY> ALL(SELECT SALARY
FROM EMPLOYEES WHERE JOB_ID='SA_MAN')
ORDER BY SALARY DESC

SELECT EMPLOYEE_ID,LAST_NAME,DEPARTMENT_ID FROM EMPLOYEES
WHERE DEPARTMENT_ID IN (SELECT DEPARTMENT_ID FROM DEPARTMENTS 
WHERE LOCATION_ID IN(SELECT LOCATION_ID FROM LOCATIONS WHERE CITY LIKE'T%'))

SELECT LAST_NAME,SALARY,DEPARTMENT_ID,AVG(SALARY) FROM EMPLOYEES WHERE SALARY>(SELECT AVG(SALARY)
FROM EMPLOYEES)
GROUP BY DEPARTMENT_ID
ORDER BY AVG(SALARY)

SELECT LAST_NAME FROM EMPLOYEES E WHERE NOT EXISTS(SELECT 
MANAGER_ID  FROM EMPLOYEES F WHERE E.EMPLOYEE_ID=F.MANAGER_ID )

SELECT * FROM EMPLOYEES WHERE LAST_NAME IN('Ernst',
'Lorentz',
'Rajs',
'Davies',
'Matos')

SELECT LAST_NAME FROM EMPLOYEES E WHERE SALARY<(SELECT AVG(SALARY) FROM EMPLOYEES D WHERE
E.DEPARTMENT_ID=D.DEPARTMENT_ID)

SELECT LAST_NAME FROM EMPLOYEES WHERE SALARY <
(SELECT AVG(SALARY) FROM EMPLOYEES GROUP BY DEPARTMENT_ID)  AND
DEPARTMENT_ID IN (SELECT DEPARTMENT_ID FROM (
SELECT DEPARTMENT_ID,AVG(SALARY) FROM EMPLOYEES GROUP BY DEPARTMENT_ID) D )


SELECT LAST_NAME FROM EMPLOYEES E WHERE EXISTS(SELECT HIRE_DATE FROM EMPLOYEES D WHERE
E.DEPARTMENT_ID=D.DEPARTMENT_ID AND D.HIRE_DATE>E.HIRE_DATE AND D.SALARY>E.SALARY)

SELECT SUM(SALARY)*1/8 FROM EMPLOYEES 


SELECT DEPARTMENT_ID,SUM(SALARY) FROM EMPLOYEES E   
WHERE E.DEPARTMENT_ID=D.DEPARTMENT_ID
GROUP BY DEPARTMENT_ID> (
SELECT SUM(SALARY)*1/8 FROM EMPLOYEES)

SELECT DEPARTMENT_ID,SUM(SALARY) FROM EMPLOYEES WHERE DEPARTMENT_ID>(SELECT SUM(SALARY)*1/8 FROM EMPLOYEES)