SELECT DEPARTMENT_ID FROM EMPLOYEES WHERE  JOB_ID!='ST_CLERK'
SELECT DEPARTMENT_ID FROM EMPLOYEES INTERSECT
( SELECT DEPARTMENT_ID FROM EMPLOYEES WHERE JOB_ID ='ST_CLERK')

SELECT COUNTRY_ID,COUNTRY_NAME FROM COUNTRIES  INTERSECT (SELECT L.COUNTRY_ID,C.COUNTRY_NAME
FROM COUNTRIES C,LOCATIONS L WHERE L.COUNTRY_ID=C.COUNTRY_ID)

SELECT JOB_ID,DEPARTMENT_ID FROM EMPLOYEES
WHERE DEPARTMENT_ID=10
UNION SELECT JOB_ID,DEPARTMENT_ID FROM EMPLOYEES
WHERE DEPARTMENT_ID=20
UNION SELECT JOB_ID,DEPARTMENT_ID FROM EMPLOYEES
WHERE DEPARTMENT_ID=50

SELECT EMPLOYEE_ID,JOB_ID FROM EMPLOYEES
INTERSECT
SELECT EMPLOYEE_ID,JOB_ID FROM JOB_HISTORY

SELECT JOB_ID FROM EMPLOYEES
SELECT * FROM JOBS
SELECT * FROM EMPLOYEES
SELECT * FROM DEPARTMENTS
SELECT last_name, salarY,department_Id FROM EMPLOYEES
WHERE LAST_NAME ='MOURGOS
