CREATE FUNCTION [dbo].[TOT_EMP] () RETURNS VARCHAR(100)
AS
BEGIN
DECLARE @TOTAL INTEGER;
DECLARE @STR VARCHAR(100);

SELECT @TOTAL=COUNT(*) FROM EMPLOYEES;
SET @STR=[dbo].[FUN_CALL_FUN]();

RETURN CONCAT(@STR,CAST(@TOTAL AS VARCHAR));

END


CREATE OR ALTER FUNCTION [dbo].[FUN_CALL_FUN] () RETURNS VARCHAR(100)
AS
BEGIN

RETURN 'Total Employee = ';

END

CREATE OR ALTER PROCEDURE [dbo].[FUN_CALL] AS
BEGIN

DECLARE @TOTAL_EMP_CNT VARCHAR(100);
SET @TOTAL_EMP_CNT = [dbo].[TOT_EMP]();

PRINT(@TOTAL_EMP_CNT);
END