CREATE OR ALTER PROCEDURE L1 AS
BEGIN
DECLARE @i INTEGER,@STR VARCHAR(100);
SET @i=1;
SET @STR=' ';
WHILE (@i<=10)
BEGIN
SET @STR=@STR+CAST(@i AS VARCHAR)+' ';
SET @i+=1;
END
PRINT(@STR)
END